#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(
  // ╭─────────────────────────────────────────────╮ ╭─────────────────────────────────────────────╮
          KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Z,    KC_U,    KC_I,    KC_O,    KC_P,
  // ├─────────────────────────────────────────────┤ ├─────────────────────────────────────────────┤
       KC_A, MT(MOD_LALT,KC_S), MT(MOD_LSFT,KC_D), MT(MOD_LCTL,KC_F),    KC_G,    KC_H, MT(MOD_LCTL | MOD_RCTL,KC_J), MT(MOD_LSFT | MOD_RSFT,KC_K), MT(MOD_LALT,KC_L),    KC_PMNS,
  // ├─────────────────────────────────────────────┤ ├─────────────────────────────────────────────┤
      LT(4,KC_Y),    KC_X,    KC_C,    KC_V,   KC_B,   KC_N,    KC_M,    KC_COMM,    KC_DOT, LT(4,KC_SLSH),
  // ├─────────────────────────────────────────────┤ ├─────────────────────────────────────────────┤
	             LT(3,KC_ESC),KC_SPC, LT(1,KC_TAB), LT(6,KC_BSPC), LT(5,KC_ENT),KC_RSFT),
//                   ╰───────────────────────────╯ ╰───────────────────────────╯

	[1] = LAYOUT(S(KC_INS),    KC_PGUP, G(KC_UP),    KC_PGDN,    KC_NO,    KC_NO,    KC_HOME,    KC_UP,    KC_END,    KC_NO,    KC_LSFT, G(KC_LEFT), G(KC_DOWN), G(KC_RGHT),    KC_NO,    KC_NO,    KC_LEFT,    KC_DOWN,    KC_RGHT,    KC_RSFT,    KC_ESC,    KC_NO,    KC_NO,    KC_LGUI,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,
	                 EE_CLR,    KC_NO,    KC_TRNS,    KC_NO,    KC_NO,    KC_RCTL),
//                   ╰───────────────────────────╯ ╰───────────────────────────╯
	[2] = LAYOUT(KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_LGUI,    KC_LALT,    KC_LCTL,    KC_LSFT,    KC_NO,    KC_CAPS,    KC_LEFT,    KC_DOWN,    KC_UP,    KC_RGHT,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_INS,    KC_HOME,    KC_PGDN,    KC_PGUP,    KC_END,
	                  KC_NO,  KC_TRNS,    KC_NO,    KC_ENT,    KC_NO,    KC_BSPC),
//                   ╰───────────────────────────╯ ╰───────────────────────────╯

	[3] = LAYOUT(
	KC_ESC, RGB_RMOD, RGB_TOG, RGB_MOD,    KC_NO,    KC_NO, RGB_RMOD, RGB_TOG, RGB_MOD,    KC_NO,
  // ├─────────────────────────────────────────────┤ ├─────────────────────────────────────────────┤
      KC_MPRV,  KC_VOLD,  KC_MUTE, KC_VOLU, KC_MNXT,  KC_MPRV,    KC_VOLD,    KC_MUTE,    KC_VOLU,    KC_MNXT,
  // ├─────────────────────────────────────────────┤ ├─────────────────────────────────────────────┤
	  KC_NO,  KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,
  // ├─────────────────────────────────────────────┤ ├─────────────────────────────────────────────┤
	                  KC_TRNS,  KC_MPLY,  QK_BOOT, KC_MSTP,   KC_NO,  KC_MPLY),
//                   ╰───────────────────────────╯ ╰───────────────────────────╯
	[4] = LAYOUT(CUSTOM(8),    KC_NO,    KC_NO, CUSTOM(0), CUSTOM(2), CUSTOM(2), CUSTOM(0),    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_LGUI,    KC_LCTL,    KC_LSFT, TG(0), TG(0),    KC_LSFT,    KC_LCTL,    KC_LALT,    KC_LGUI,    KC_TRNS, CUSTOM(6), CUSTOM(4),    KC_NO, TG(4), RESET,    KC_NO, CUSTOM(4), CUSTOM(6),    KC_TRNS,    KC_MS_BTN2,    KC_MS_BTN1,    KC_MS_BTN3,    KC_MS_BTN3,    KC_NO,    KC_MS_BTN1),
	[5] = LAYOUT(KC_ESC,    KC_F7,    KC_F8,    KC_F9,    KC_NO,    KC_F10,    KC_7,    KC_8,    KC_9,    KC_LGUI,    KC_NO,    KC_F4,    KC_F5,    KC_F6,    KC_NO,    KC_F11,    KC_4,    KC_5,    KC_6,    KC_BSPC,    KC_NO,    KC_F1,    KC_F2,    KC_F3,    KC_NO,    KC_F12,    KC_1,    KC_2,    KC_3,    KC_0,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_TRNS,    KC_TRNS),
	[6] = LAYOUT(S(KC_5), S(KC_MINS), S(KC_SLSH), S(KC_1),    KC_COMM,    KC_LBRC,    KC_RBRC, S(KC_6), S(KC_8),    KC_QUOT, S(KC_EQL), S(KC_2), S(KC_4),    KC_SLSH, S(KC_GRV), S(KC_9), S(KC_0), S(KC_COMM), S(KC_DOT), S(KC_QUOT), S(KC_7),    KC_BSLS, S(KC_3), S(KC_BSLS),    KC_EQL, S(KC_SCLN),    KC_SCLN, S(KC_LBRC), S(KC_RBRC),    KC_GRV,    
  // ├─────────────────────────────────────────────┤ ├─────────────────────────────────────────────┤
	                     KC_NO,    KC_NO,    KC_NO,    KC_TRNS,    KC_NO,    EE_CLR),
	//                   ╰───────────────────────────╯ ╰───────────────────────────╯

	[7] = LAYOUT(KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS),
	[8] = LAYOUT(KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)




